# Generated by Django 3.2.3 on 2021-07-23 03:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('popularity', models.IntegerField()),
                ('duration_ms', models.FloatField(null=True)),
                ('explicit', models.BooleanField(null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('acousticness', models.FloatField(null=True)),
                ('danceability', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('instrumentalness', models.FloatField(null=True)),
                ('liveness', models.FloatField(null=True)),
                ('loudness', models.FloatField(null=True)),
                ('speechiness', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('valence', models.FloatField(null=True)),
                ('key', models.IntegerField(null=True)),
                ('mode', models.IntegerField(null=True)),
                ('time_signature', models.IntegerField(null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
                ('header_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('header_image_thumbnail_url', models.CharField(blank=True, max_length=100, null=True)),
                ('song_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('song_image_thumbnail_url', models.CharField(blank=True, max_length=100, null=True)),
                ('genius_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lyrics', models.TextField(blank=True, default='No lyrics at the moment', null=True)),
                ('artists', models.ManyToManyField(blank=True, to='songs.Artist')),
            ],
        ),
    ]
