# Generated by Django 3.2.3 on 2021-07-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_artist_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
                ('duration_ms', models.FloatField()),
                ('explicit', models.BooleanField()),
                ('release_date', models.DateField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('key', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('artists', models.ManyToManyField(blank=True, to='songs.Artist')),
            ],
        ),
    ]
