# Generated by Django 3.2.3 on 2021-07-15 05:39

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='song',
            name='genius_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='header_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='header_thumbnail_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='No lyrics at the moment'),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_thumbnail_image_url',
            field=models.URLField(blank=True),
        ),
    ]
