# Generated by Django 3.2.3 on 2021-07-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20210715_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='header_thumbnail_image_url',
            new_name='header_image_thumbnail_url',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_thumbnail_image_url',
            new_name='song_image_thumbnail_url',
        ),
    ]
