# Generated by Django 3.2.3 on 2021-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
